# Generated by Django 4.1 on 2022-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='xyz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
