# Generated by Django 4.1 on 2022-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_alter_check_xyz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='xyz',
        ),
        migrations.AddField(
            model_name='check',
            name='abc123',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
